spring:
  batch:
    job:
      enabled: false
  datasource:
    baoxian:
      driver-class-name: com.mysql.cj.jdbc.Driver
      maxActive: 10
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      poolPreparedStatements: false
      validationQuery: "SELECT 1+1"
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      jdbc-url: jdbc:mysql://localhost:3306/baoxian
      username: root
      password: password

    h2:
      jdbc-url: jdbc:h2:mem:mydb
      driver-class-name: org.h2.Driver
#      schema: classpath:schema:schema-all.sql
#      driver-class-name: com.mysql.jdbc.Driver

#  jpa:
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5Dialect


